### ISSUE TITLE
Fixing bug for window resize event (adjusting draggable events).

### ISSUE THREAD

**Issue by christophorus** [themouette/jquery-week-calendar#104]
$(window).bind(this.options.resizeEvent, function() {
            self._resizeCalendar(); 
        self.element.find('.wc-cal-event').each(function() {
                var $calEvent = $(this);
                $calEvent.draggable('destroy');
                self._addDraggableToCalEvent($(this).data('calEvent'), $calEvent);
        });
 });

**Comment by K-Phoen** [comment]
Can you explain a bit more the bug you encountered? I could not find any bug after having resized the window several times.

I close this issue until I have more information, feel free to reopen it :)
