### ISSUE TITLE
FFox raises undefined calEvent.end.setFullYear exception

### ISSUE THREAD

**Issue by LoneCoder** [themouette/jquery-week-calendar#11]
calEvent.end.setFullYear(start.getFullYear()); within _renderEvents: 

```
    while( start.getDay() < endDay ){
        calEvent.start = start;
        //end of this virual calEvent is set to the end of the day

        calEvent.end.setFullYear(start.getFullYear());
```

**Comment by andrzej-aa** [comment]
I can't reproduce your issue. Could you show the code that you are using?

**Comment by LoneCoder** [comment]
Sorry, It happens if you don't load external date.js library in a json context. 
I'ven't noticied this changement.
