### ISSUE TITLE
 how to prevent the event creation for particular date with time slot ?

### ISSUE THREAD

**Issue by jmaniv** [themouette/jquery-week-calendar#111]
thanks for providing wonderful plugin.
Now I want to prevent the event creation for past date/time.
I found "beforeEventNew" in https://github.com/themouette/jquery-week-calendar/pull/99.
Then I just return false from beforeEventNew when today_date is less than new Date(calEvent.start) in demo.js. like

beforeEventNew : function(calEvent, $event) {
var today = new Date();
    if (calEvent.start.getTime() < today.getTime()) {
    alert(calEvent.start)
    //return false;
},

Unfotunetly I couldn't get calEvent.start

how to prevent the event creation for past date and particular slot ?

**Comment by bangiamanu** [comment]
Use the new API  https://github.com/themouette/jquery-week-calendar/wiki/Script-options  and use the  allowEventCreation :false

**Comment by K-Phoen** [comment]
The information contained by the wiki was incorrect. I just updated it to reflect the reality.
In fact, the `beforeEventNew` callback receives two arguments: the dom event, and some data (see the wiki for more details on this). Therefore, your code should look like this:

``` js
beforeEventNew: function($event, ui) {
  if (ui.calEvent.start < new Date()) {
    // prevent other handlers to interfere with our decision
    $event.stopPropagation();

    // and prevent the creation
    return false;
  }
},
```
