### ISSUE TITLE
Causing Freezing, Unresponsive Script

### ISSUE THREAD

**Issue by twisterghost** [themouette/jquery-week-calendar#113]
I am trying to implement an instance of the weekly calendar and followed the basic setup putting the calendar into a div within my page. However, upon loading it begins scrolling to the time, then gets caught up and freezes. If I stop the script, it then fills the calendar with all 24-hour long events and acts strangely, freezing often.

Is this a known issue? Do you need more information to help this bug? Any suggestions about fixes would be extremely helpful.

**Comment by thorst** [comment]
I think more info is needed. Provide the data your trying to bind, and the browser your using. Also jquery and ui versions may help.

I am not having this issue

**Comment by K-Phoen** [comment]
Without additional details, I have no choice but to close this issue. Feel free to reopen it if the bug is still present.
