### ISSUE TITLE
summertime vs wintertime

### ISSUE THREAD

**Issue by thetomtom** [themouette/jquery-week-calendar#122]
Hi there,

first of all: I tried loads of calendars BUT THIS IS DEFINITLY THE BEST of all. Great work.

But for now, I'm stucking. I tryed to create some recurring events, as it is described like here:
http://www.packtpub.com/article/calendars-jquery-1.3-php-jquery-week-calendar-plugin-2

Thats not a real problem, but I ran into the summer/wintertime problem :(:( And I have no Idea how to fix.

For example, if I add a recurring event which reaches over the wintertime into the summertime, and it shoukd start at 9am, in summertime it'll start at 10am :(

Can anyone help me to figure out how to handle this?

rgrds

Tom

**Comment by themouette** [comment]
Hi,

Is the rendering the issue or the generated list ?
please give an event set rendering badly so it is possible to investigate.

Julien.

**Comment by thetomtom** [comment]
Hi Julien,

I guess its the generated list itself. Actual, I push all entrys to a mysql. inside the table, there is a field for start and end. If I setup an event from february to april, and the switch from winter top summertime is in the last week of march, the time when the event will start changes automatically in all following entrys. 

In the end, it might be a problem of the datehandling , and not a problem of the calendar itself. 
I sotre dates inside the db by date('c', ...... Now, I fixed this issue by using the GMT with gmdate('c', ....

It works.

Anyway, this calendar is very genius. I LIKE :):)

**Comment by K-Phoen** [comment]
> It works.

Great, so I close this issue :)
