### ISSUE TITLE
Ghost event when dropping

### ISSUE THREAD

**Issue by sucotronic** [themouette/jquery-week-calendar#124]
In line [1779](https://github.com/themouette/jquery-week-calendar/blob/master/jquery.weekcalendar.js#L1779) there is a .hide() call that should be replaced by a .remove(), if not, a jquery ghost element is keep in the calendar that knock with other real, non ghost, events.

**Comment by themouette** [comment]
makes sens either.

**Comment by K-Phoen** [comment]
I agree with @themouette.

@sucotronic, what about submitting a PR to fix this? :)

**Comment by sucotronic** [comment]
done https://github.com/themouette/jquery-week-calendar/pull/128

**Comment by K-Phoen** [comment]
Fixed by https://github.com/themouette/jquery-week-calendar/pull/128
