### ISSUE TITLE
eventResize call reorder

### ISSUE THREAD

**Issue by sucotronic** [themouette/jquery-week-calendar#125]
In line [1821](https://github.com/themouette/jquery-week-calendar/blob/master/jquery.weekcalendar.js#L1821) there is the call of resize event. It should be reordered, to be called before refreshing the view, so if you change the event, if will be displayed correctly:

```
//trigger resize callback
options.eventResize(newCalEvent, calEvent, $calEvent);
self._refreshEventDetails(newCalEvent, $calEvent);
self._positionEvent($weekDay, $calEvent);
self._adjustOverlappingEvents($weekDay);
```

**Comment by themouette** [comment]
Hi,
it seems to make sense.
we'll look into it.

**Comment by K-Phoen** [comment]
Same thing here, could you write a PR please?

**Comment by sucotronic** [comment]
done https://github.com/themouette/jquery-week-calendar/pull/128

**Comment by K-Phoen** [comment]
fixed by https://github.com/themouette/jquery-week-calendar/pull/128
