### ISSUE TITLE
Regression: Undefined calEvent Error on Drag and Drop

### ISSUE THREAD

**Issue by csytan** [themouette/jquery-week-calendar#130]
When dragging and dropping an event (using latest version in Master), there is an error caused by an undefined calEvent.
"Uncaught TypeError: Cannot read property 'start' of undefined"

To reproduce:
1. Download latest version of jquery-week-calendar (as of this post April 4th, 2012)
2. Open "weekcalendar_demo_4.html" and drag and drop an event
3. Error is shown in the js console 

This bug is not present in the older version hosted here:
http://themouette.github.com/jquery-week-calendar/full_demo/weekcalendar_full_demo.html

**Comment by K-Phoen** [comment]
Hi,

Can you check [this commit](https://github.com/themouette/jquery-week-calendar/commit/874715d439822ee65b40646e0146b83bd53d8447) and tell me if it fixes your problem?

Thanks for your feedback ;)

**Comment by csytan** [comment]
Hey there,

Thanks for the quick reply!  Unfortunately I still get the same error.  It's within this method:

_findWeekDayForEvent()

**Comment by K-Phoen** [comment]
Should be better now, can you confirm?

**Comment by csytan** [comment]
The new version fixes the problem. Thanks!
