### ISSUE TITLE
displaying events with equal start and end

### ISSUE THREAD

**Issue by dittodhole** [themouette/jquery-week-calendar#14]
this is a dirty fix, but it will do the trick ...

change line 1274 from
    if ( start < initialEnd ) {
to
    if ( start <= initialEnd ) {

change line 1508 from
    $calEvent.css({top: pxTop, height: pxHeight});
to
    var pxHeightFallback = pxPerMillis \* (60 / options.timeslotsPerHour) \* 60 \* 1000;
    $calEvent.css({top: pxTop, height: pxHeight || pxHeightFallback}); 

if someone has got a better solution, please post!

**Comment by andrzej-aa** [comment]
There's usually no need to use it, but probably it would be included in the project (in my fork i included it).

**Comment by themouette** [comment]
I merged your fork andrzej-aa, so it now is part of the main branch.
