### ISSUE TITLE
_findWeekDayForEvent function does not find events correctly

### ISSUE THREAD

**Issue by goodkiller** [themouette/jquery-week-calendar#144]
If you are using scheduler with users, then calendar does not find users events because $.inArray($(this).data('wcUserId'), user_ids) function search string values in user_ids array, but those should be integer. This issue is somewhere on line 1630.

Solution:

user_ids = [user_ids];

should be replaced:

user_ids = [parseInt(user_ids)];

**Comment by K-Phoen** [comment]
Why do you assume that an ID should be an integer ? I use alphanumeric slugs instead of integers ...

WeekCalendar allows you to override the set/getEventUserId methods so that it works with your model. I think that either your data or your implementation of these methods is incorrect :)
