### ISSUE TITLE
Disable Add new Item/drag/expand

### ISSUE THREAD

**Issue by andyc209** [themouette/jquery-week-calendar#145]
I am building this into a SQL driven calendar but want to disable the ability to click on the calendar and it puts in an entry, also disable dragging and scrolling. I am creating my own entry screen to feed the dates into the database so do not want any changes made on the screen. 

Tried changing  allowEventCreation: true, to  allowEventCreation: false, and this does not seem to work - is there anything else i need to change?

**Comment by themouette** [comment]
you can set the `readonly` option to true, and that should do the trick.
By the way, there is a google group for questions, issues are for issues only.

Julien.
