### ISSUE TITLE
businessHours ?

### ISSUE THREAD

**Issue by Shuunen** [themouette/jquery-week-calendar#15]
I have used many option and they all work , but I tryed to put businessHours option but it not work, is my syntax correct ?

businessHours: [{"start": 8, "end": 18, limitDisplay: true}]

I also try : businessHours: [{start: 8, end: 18, limitDisplay: true}]

I upload a zip file with test files : http://www.mediafire.com/?0d9lc482n1he7ed

Thanks !

**Comment by themouette** [comment]
Hi,

correct syntax is businessHours: {"start": 8, "end": 18, limitDisplay: true}, without the square backets.

Julien.

**Comment by Shuunen** [comment]
Thank you so much, great project , great support :)
