### ISSUE TITLE
how can i made a XML request using ajax call for event data?

### ISSUE THREAD

**Issue by sijuthankachan** [themouette/jquery-week-calendar#155]
sample request url 

```
"http://test.com/services/getevent"      
```

and  its gives a XML file dynamically from the remote server 
so i think we need a callback function to retrieving remotely.

and sample response XML

```
<list>
  <item>
       <id>1</id>
       <title>....</title>
       <start>...</start>
       <end>...</end>
   </item>
  <item>
       <id>2</id>
       <title>....</title>
       <start>...</start>
       <end>...</end>
   </item>
  <item>
       <id>3</id>
       <title>....</title>
       <start>...</start>
       <end>...</end>
   </item>
</list>
```

please help to write code to get the event data from the xml request using the ajax call

```
data : function(start, end, callback) {
..?//Ajax Call
..?
..?
},
```

**Comment by K-Phoen** [comment]
You should ask this kind of questions directly on the mailing list : http://groups.google.com/group/jquery-week-calendar
