### ISSUE TITLE
Calculate wc-scrollable-grid height fail

### ISSUE THREAD

**Issue by teklakct** [themouette/jquery-week-calendar#169]
Using jquery-1.8.2 on chrome.

When try to get .outerHeight() of: 
- headerHeight
- navHeight
  this method return object and scrollContainerHeight is calculated as NaN.
  When I add [includeMargin ] to false it's work for me.

This is in _resizeCalendar method on line 562.

I not sure that only my problem.

**Comment by peteb** [comment]
Yes I have this problem as well. I'm sending `false` to outerHeight which makes it work.

**Comment by teklakct** [comment]
WoW, this is a very old Issue. I've already forgot about it. 

I don't remember what helped me fix this problem but IMHO making changes in core/lib files is not a good way.
