### ISSUE TITLE
Would be great to add public functions for single day prev/next.

### ISSUE THREAD

**Issue by ghost** [themouette/jquery-week-calendar#18]
It would be very useful to have single day prev/next functions available, as follows:

<pre>
prevDay : function() {
    var newDate = new Date(this.element.data("startDate").getTime() - MILLIS_IN_DAY);
    this._clearCalendar();
    this._loadCalEvents(newDate);
},
</pre>

If that is undesirable, may I suggest adding a public function that returns the current calendar start date, so that we can achieve single day prev/next using the gotoDate function.

**Comment by dittodhole** [comment]
there are already such functions available ... `next()` and `prev()` - these will do the movement according to the `daysToShow` field

**Comment by themouette** [comment]
I close this one.
thanks for your answer(s) by the way.

**Comment by ghost** [comment]
But I am already showing 7 days in my view, and using next() and prev() to skip to the next/prev week.  What I want to do is scroll the calendar _one_ day forward and back.  

So far I have not found any way to do this without adding my own function to the script.

**Comment by themouette** [comment]
If you want to override a function with custom code, you might try this:

`
 $('#calendar').data('weekcalendar').next = function(){/* your code */};
`

I did not test it, but this is the way you can extend ui widgets.

**Comment by ghost** [comment]
I wasn't aware of this.  Thanks.
