### ISSUE TITLE
IE Support

### ISSUE THREAD

**Issue by Shmythe** [themouette/jquery-week-calendar#24]
I was wondering if there are any tricks to get this to work with IE8/9.

It seems to work fine in everything else but in IE 8/9 both don't seem to render the events. I have checked and the data is being passed to the to "data" option.

Any ideas you could give me would be much appreciated.

(With the exception of telling me not to use IE, I would gladly stop, but my users would throw a fit)

**Comment by dittodhole** [comment]
from my experience: there's no problem with IE 8/9 unless you are using jQuery 1.5 :)

**Comment by Shmythe** [comment]
Well I have been having this problem with all flavors of jQuery. Though I am now using 1.5.1.  And I have now got it to work with IE9, but not with anything lower then that.  I am not sure if it is because I am using a function to call the calendar information or what, but it just will not display any of my events.

**Comment by edgarinvillegas** [comment]
Please send a link of a page showing the bug "live"

**Comment by glide1** [comment]
I am also experiencing this issue with IE 8. It might be difficult to provide credentials for you seeing as it's a live site.

**Comment by glide1** [comment]
I figured out what was going on. I was passing in dates as ISO8601 format to IE 8 and the Date.parse was returning NaN. Returning the date as milliseconds worked.

**Comment by K-Phoen** [comment]
I therefore consider this issue as resolved. Feel free to reopen it if I'm wrong.
