### ISSUE TITLE
Multiple instances aborts each other ajax requests

### ISSUE THREAD

**Issue by Rockclimber** [themouette/jquery-week-calendar#31]
Hello everyone,
I'm new here and don't have commit privilege.
I've already improved this scirpt for my purposes like that 

Don't use global variable! like here(line 19)
(function($) {
    var _currentAjaxCall;

Put it as object option instead. like here(line22)
 options: {
    _currentAjaxCall: false,
         date: new Date(),

and now when you want to talk to this variable add "options." each time like:
options._currentAjaxCall
these are in lines 1113, 11211, 1132

cheers,
Pawel

**Comment by themouette** [comment]
this was fixed with last release
