### ISSUE TITLE
CSS - column header lines are not aligned with grid (Firefox)

### ISSUE THREAD

**Issue by ghost** [themouette/jquery-week-calendar#38]
Using Firefox 3.6.13 on Ubuntu, the date column headers do not align with the grid.  See screen capture:  http://twitpic.com/40yhjq
That's using jquery-week-calendar.css from today (2011-02-18).

I can confirm that the alignment is good on Chromium 9.0 (Ubuntu).

**Comment by themouette** [comment]
is it any better ?

**Comment by ghost** [comment]
No, that's worse.  On Firefox the alignment is still incorrect, but with this latest file I also lose the border line along the left edge of the calendar: http://twitpic.com/41h312

On Chromium, the alignment remains correct, but I also lose the border line along the left edge: http://twitpic.com/41h3kf

**Comment by themouette** [comment]
Hi,
the line is gone as it was causing issues on quite every browsers, there were a slight misalignment.

If you find a way to correct it, do not hesitate to share, but as I cannot test on your browser, I do not know how I could fix it.

thanks for the report,

Julien

**Comment by K-Phoen** [comment]
Mozilla discontinued support for Firefox 3.6 on April 24, 2012. Therefore, I don't plan to fix this bug as I can not reproduce it on recent browsers.

Feel free to make a PR if you really want this bug fixed.
