### ISSUE TITLE
Events are treated as overlapping when End Time = Start Time of next event

### ISSUE THREAD

**Issue by mrpanda** [themouette/jquery-week-calendar#4]
As part of playing with the Demo, I added an event to the JSON events that went from 6pm to 12:00am (midnight) and another event from 12am to 8:00am - these were then rendered as overlapping.

As part of scheduling, it is common for the next event to begin at the same time that the prior event finishes. Therefore, the overlap functionality should only consider end times that are > start times, and allow end times = start times.

**Comment by themouette** [comment]
this was cloased some time ago...
