### ISSUE TITLE
Error: b("<div></div>").addClass("ui-widget-overlay") is undefined Source File: http://staging.indusnettechnologies.com:81/noema.com/dalmorocha/sgd/libs/jquery-ui-1.8rc3.custom.min.js

### ISSUE THREAD

**Issue by sauravlnp** [themouette/jquery-week-calendar#44]
I am keep getting this error when adding 3 or more events.After creating 2 events when i tried to add 3 events i am getting this error and event does not add.Please help me..

Error: b("<div></div>").addClass("ui-widget-overlay") is undefined
Source File: http://staging.indusnettechnologies.com:81/noema.com/dalmorocha/sgd/libs/jquery-ui-1.8rc3.custom.min.js
Line: 199

please help....

**Comment by sauravlnp** [comment]
please help.Can anybody tell me how to fix this?

**Comment by themouette** [comment]
come on, update your jquery ui vesion, latest stable is 1.8.10, you are using a release candidate !

**Comment by sauravlnp** [comment]
Thanks friend. :)
