### ISSUE TITLE
Support with Google Calendar

### ISSUE THREAD

**Issue by diamondback15** [themouette/jquery-week-calendar#45]
Hi, 

How can I sync the calendar with google calendar ?

Thank You

Julien

**Comment by themouette** [comment]
Hi,

up to now there is nothing, but you might have a look to [arshaw full-calendar](http://arshaw.com/fullcalendar/docs/google_calendar/) as this is integrated.

If you work on something to adapt it to jquery week calendar, do not hesitate to share your work :)

Julien

**Comment by diamondback15** [comment]
Yes, I already saw this calendar. Can I memorize an Event. When I click on the calendar I create an event and when I refresh obviously there's a reset. How can I store those event?

**Comment by themouette** [comment]
maybe you can first have a look to the wiki, that's a good start.

**Comment by diamondback15** [comment]
Yes that's what I did and I didn't found anything about storing in a database.  Does it work with xml, mysql or text file? I saw something about json but I really don't know how it function.

**Comment by themouette** [comment]
there is no backend provided with the calendar, you have to use callbacks to send events to your backend application.
