### ISSUE TITLE
Impossible to drag event to first day in multi user view

### ISSUE THREAD

**Issue by pawelantczak** [themouette/jquery-week-calendar#47]
Hello. 
I find out that it impossible to drag event to first user, first day. 
Use-case: http://themouette.github.com/jquery-week-calendar/weekcalendar_demo_3.html 
This bug exist only if you want to move event from today.

**Comment by themouette** [comment]
this is already reported in issue [#37](https://github.com/themouette/jquery-week-calendar/issues#issue/37)
