### ISSUE TITLE
the refresh method remove all new events

### ISSUE THREAD

**Issue by klapaudius** [themouette/jquery-week-calendar#50]
Hi,

to reproduce it :  
1. create a new event in current week  
2. click on the Save button  
3. click on Today button  
4. Voila (I'm french to ^^ )

Thanks for your work on this nice project.

**Comment by themouette** [comment]
Hi,

this is the expected behaviour as described in the doc.
you need a backend to implement data persistance, and refresh just fetch data from server again.

Cheers,

Julien.
