### ISSUE TITLE
Calendar is completely off

### ISSUE THREAD

**Issue by djpate** [themouette/jquery-week-calendar#51]
First of all thanks for this script !

I'm trying to merge the calendar with google calendar.

I managed to fetch the events in JSON format here is an example.

```
[
```

{"id":"0vph199u88ptubouu659cvuruo","title":"13h 15h","start":"2011-03-29T13:00:00.000+02:00","end":"2011-03-29T15:00:00.000+02:00"},
{"id":"if1fa7d9u13r7sapu4juqkj4pk","title":"10h 12h","start":"2011-03-29T10:00:00.000+02:00","end":"2011-03-29T12:00:00.000+02:00"}]

So there is an event from 10 to 12 and another one from 13 to 15 but In the calendar 

But in the calendar It's not displayed at all like that

http://i51.tinypic.com/xbwo4z.jpg

Any ideas ?

**Comment by djpate** [comment]
For some reason an event at top:0px appears at 10 am instead of 8am with business hours set from 8am to 8pm

**Comment by djpate** [comment]
It seems my bug is not accurate i'm going to open a new one

**Comment by cheluis** [comment]
Dude, I have the same  issue, which is the new issue? It is still open? Thanks

**Comment by djpate** [comment]
If I remember right it was because I modified the CSS too much...

**Comment by cheluis** [comment]
Hahaha well I guess I did the same... well, Thanks

**Comment by cheluis** [comment]
So, any hint? I can't see what's wrong...

**Comment by cheluis** [comment]
I set up the calendar in readonly mode and works fine. Seems like a  problem with resizeable's styles.

**Comment by djpate** [comment]
I cant remember but it was a problem with position fixed or something like that
