### ISSUE TITLE
Resizable dialogs

### ISSUE THREAD

**Issue by ThiefMaster** [themouette/jquery-week-calendar#53]
Dialogs where the contents do not scale automatically should not be resizable at all.

**Comment by themouette** [comment]
Hi,

I guess you talk about provided demo.

demos are demos, that mean a simple showcase to show how to use the calendar.
To use the plugin it is highly recommended to develop your own logic.

anyway, i'd be glad to merge your pull request if you provide a way to have resizable widgets in the dialog box.

cheers,

Julien.
