### ISSUE TITLE
Safari Support for remote data

### ISSUE THREAD

**Issue by gregluwinsky** [themouette/jquery-week-calendar#54]
Hi, first i want to say how amazing the plugin is, i loved it n putting it in my blog. but its just when i fire up safari both on pc n my ipad its not really loading my event, but firefox and chrome does. i return the json (setting up the json is pain in the ass for me) with the php iso format, it doesnt work so i change the code a bit to return one that looks exactly like the one on the json demo. perhaps a bug on my owm or some mistake n my json format? and if i may request, can you tell me the best practices to apply remote json on php? like what format should do php returm at best? thxxxx

**Comment by K-Phoen** [comment]
You should ask this king of stuff on the [mailing-list](http://groups.google.com/group/jquery-week-calendar). Since this is not a real issue, I close it.
