### ISSUE TITLE
"Unable to get data, error:error" occuring when leaving page

### ISSUE THREAD

**Issue by jfriedlaender** [themouette/jquery-week-calendar#55]
When navigating away from the page the calendar is on, and while the data is still being fetched, I receive the error "Unable to get data, error:error".

I have been able to fix this issue by adding: 
&& errorThrown != '' 

to the code below:

error: function(XMLHttpRequest, textStatus, errorThrown) {
                // only prevent error with jQuery 1.5
                // see issue #34. thanks to dapplebeforedawn
                // (https://github.com/themouette/jquery-week-calendar/issues#issue/34)
                if (errorThrown != 'abort' && errorThrown != '') {
                  alert('unable to get data, error:' + textStatus);
                }
              },

I am not sure if this will have any negative repercussions for error reporting, but is has fixed the problem for me.

**Comment by themouette** [comment]
Hi,

with your fix, what happens if server returns a 404 ?

Julien.

**Comment by jfriedlaender** [comment]
I don't know sorry, but I have been using this code in a fairly heavy use environment for a few months now without problem.

**Comment by themouette** [comment]
thing is this piece of code is here to tell the user there were a problem
when fetching remote data.
*
*
_It appears that with your change, there is no warning when aborting, but
there is neither when request results in an error._
_Best advice is to migrate to jquery 1.5.1 or later, but sometimes you just
can't._
*
*
_A clean solution would be to handle the server error in a onServerError
option callback, this would make it easier to override without changing
default behavior._
*
*
_what do you think about it ? another idea ?_
*
*
_Do you feel like doing it and create a pull request ?_
- *
  Julien.

**Comment by jfriedlaender** [comment]
My change is hiding the error when it is empty, but if it is empty, it's not exactly providing any useful information to the user anyway. I would think with other types of errors, it won't be empty so won't be suppressed.

I am not sure how I do pull requests, I have never done so before.
