### ISSUE TITLE
start and end date time value for event data

### ISSUE THREAD

**Issue by lagendss** [themouette/jquery-week-calendar#56]
What is exactly value for start and end date time for an event data?
I viewed json demo but it completely not functioning.
 For other demo example, it using 

"start": new Date(year, month, day, 12),"end": new Date(year, month, day, 13, 30),
but from json file, it using 
"start":"2009-05-10T13:15:00.000+10:00", "end":"2009-05-10T14:15:00.000+10:00". 

However i try to replace  "start": new Date(year, month, day, 12),"end": new Date(year, month, day, 13, 30) with "start":"2011-04-07T13:15:00.000+10:00", "end":"2011-04-07T14:15:00.000+10:00" on working but no event appear.Please help

**Comment by themouette** [comment]
Hi,

I don't think this is the right place to ask questions, please use the mailing list. 
If search a bit you'll see this question has already been answered.

And by the way, [wiki](https://github.com/themouette/jquery-week-calendar/wiki) is here to help, there is a dedicated paragraph.

Cheers,

Julien
