### ISSUE TITLE
event repeated

### ISSUE THREAD

**Issue by bbenjii123** [themouette/jquery-week-calendar#6]
Hello

I would like to know how to create few events in the week ? I would like to create a periodicity for an event and when the user fill this information, the event is repeated in the week.
I have took the jquery-week-calendar from themouette and in the /full_demo/demo.js, I add this after the line 59 :

```
id++;
calEvent.id = id;
calEvent.start = new Date(startField.val());
calEvent.start = calEvent.start.setTime(calEvent.start.getTime() +  86400000);
calEvent.end = new Date(endField.val());
calEvent.end = calEvent.end.setTime(calEvent.end.getTime() +  86400000);
calEvent.title = titleField.val();
calEvent.body = bodyField.val();

$calendar.weekCalendar("updateEvent", calEvent);
```

and when I create an event on 5th July, it brings forward to 6th July

**Comment by themouette** [comment]
this is not an issue, you're screwing your pointers / references up.
there is already a thread about that in the mailing list.

for recurency, you have to implement it on server side, or you have to learn javascript for real.

Julien.
