### ISSUE TITLE
tooltip or dialog on event

### ISSUE THREAD

**Issue by clochettefee** [themouette/jquery-week-calendar#64]
Hi,

I think there's a problem on the _setupEventDelegation:
with the onmouseover and onmouseout which take only the .wc-cal-event.

I changed this like that for me :

if ($target.hasClass('wc-cal-event')) {
 options.eventMouseover($target.data('calEvent'), $target, event);
 }
by

var $calEvent = $target.hasClass('wc-cal-event') ? $target : $target.parents('.wc-cal-event');
        if($calEvent.length){

```
        options.eventMouseover($calEvent.data('calEvent'), $calEvent, event);
    }
```

and with this I can have my tooltip ok even when the event is too short to be able to show it. this permitt to use tooltip even on wc-time and wc-title part of the event.

What do you think about it ?

**Comment by K-Phoen** [comment]
This should be fixed now, sorry for the delay.
