### ISSUE TITLE
PB with users

### ISSUE THREAD

**Issue by clochettefee** [themouette/jquery-week-calendar#65]
Hi,

I take users as callback in the data: options: users

{"options":{"users": ["P1","P2","T3","18","2"]},"events":[......

and it's ok.

But I would like to have it like :
{"options":{"users": [{"id"="1", "name"="P1"},{"id"=2, "name" = "P2",........

to have either the database id which corresponds the user.

I don't know how to manage.

Can you help me please ?

**Comment by themouette** [comment]
Hi,

this is not an issue, you have to use the mailing list to ask questions.

by the way, all you need to answer this one is available in the wiki documentation: https://github.com/themouette/jquery-week-calendar/wiki/Script-options under user management option.

cheer,

Julien.
