### ISSUE TITLE
iPad not dragging and dropping

### ISSUE THREAD

**Issue by jmr74** [themouette/jquery-week-calendar#68]
Hi Everyone,

Does anyone know how to do it for iPad, the drag and drop doesn´t work properly, it grabs the entire page :(

Thanks for the help

**Comment by p4ul** [comment]
jQuery does not support touch naturally. see http://stackoverflow.com/questions/3026915/how-can-i-make-a-jquery-ui-draggable-div-draggable-for-touchscreen

**Comment by K-Phoen** [comment]
This issue duplicates the issue #5.

iPad/touch support is an important feature that we should provide, and we'll try to provide it as soon as we can.
