### ISSUE TITLE
Event drag on day 6 or day 7 of week display

### ISSUE THREAD

**Issue by rstein2000** [themouette/jquery-week-calendar#7]
The issue:  if the week calendar is displaying more than five days, there is a bug when dragging an event in the furthest day to the right of the display.

For example, let's say the calendar is set to display seven days, and day 7 (i.e., Saturday) has an event in it.  If you select that event to drag, it snaps into day 6 and cannot be moved back into day 7 without first saving it outside day 7.

To give a more detailed example, let's say the event on day 7 in the above example is Lunch from 12-1.  Somethings comes up and you have to reschedule lunch from 1-2.  So you want to drag Lunch from 12-1 on day 7 to the 1-2 slot on day 7.  But when you grab the event to move it, it pops into day 6 and is locked out of day 7!  So you have to first "save" it in day 6, and then can re-drag it back into day 7.

If this example isn't clear, please let me know.

IMPORTANT EDIT:  This bug only appears when there is a vertical scroll bar inside the calendar window.  If the div containing the calendar is resized vertically to accomodate the calendar without the calendar requiring a scroll bar to view all times in a day, dragging and dropping behaves as expected.

**Comment by themouette** [comment]
it seems like fixed to me, can you provide a test case if it still isn't ?
