### ISSUE TITLE
Multiple users using json

### ISSUE THREAD

**Issue by apurvgupta** [themouette/jquery-week-calendar#76]
Hi,
I am not very good in coding.
First of all thanks for such a wonderful plugin.
I was wondering how can i get the users using json.
This is having only an option of array.
Is it any how possible to get the users from json like we did in events.
Thanks

**Comment by themouette** [comment]
Hi,

this is not an issue, you have to use the [mailing list](http://groups.google.com/group/jquery-week-calendar) to ask questions.

by the way, all you need to answer this one is available in the wiki documentation: https://github.com/themouette/jquery-week-calendar/wiki/Script-options under user management option.

cheer,

Julien.

**Comment by apurvgupta** [comment]
Hi Thankx for such a fast reply.
But i have read wiki and could not understand how to add users straight away from database.
Though i know I am irritating you but it would be very nice if you give 5 minutes of your precious time to me.
Thanks.:)

**Comment by apurvgupta** [comment]
Hi Thankx for such a fast reply.
But i have read wiki and could not understand how to add users straight away from database.
Though i know I am irritating you but it would be very nice if you give 5 minutes of your precious time to me.
Thanks.:)

Apurv
