### ISSUE TITLE
Limit start and end dates?

### ISSUE THREAD

**Issue by cbmeeks** [themouette/jquery-week-calendar#8]
My project calls for a window of dates.  For example, May 15th to May 28th.  I would like to be able to limit the prev/next buttons to a date range like that.

I can't seem to find a solution for this.

Thanks

**Comment by dittodhole** [comment]
maybe adapting the `prev`, `prevWeek`, `next` and `nextWeek` functions to check against your constraints will do the trick ...

**Comment by andrzej-aa** [comment]
Look at my fork. I made that functionality ;)

**Comment by themouette** [comment]
pulled, I close the ticket
