### ISSUE TITLE
Wiki page missing public method "setDaysToShow"

### ISSUE THREAD

**Issue by shakerlxxv** [themouette/jquery-week-calendar#83]
The public methods wiki https://github.com/themouette/jquery-week-calendar/wiki/Public-methods is missing the "setDaysToShow" method. Its in the code, and it works great.

When I tried using the "option", "daysToShow" route, it wasn't working quite as I'd like it to, so adding this to the wiki page would be great.

Thanks!

**Comment by K-Phoen** [comment]
Done, thanks !
