### ISSUE TITLE
Minor code optimization

### ISSUE THREAD

**Issue by dittodhole** [themouette/jquery-week-calendar#87]
In the method `_renderCalendarBodyOddEven` there are two checks against `displayOddEven` ... the second one can be removed safely!

**Comment by themouette** [comment]
Hi,
Any chance you create a pull request ?

**Comment by dittodhole** [comment]
yep - done

**Comment by themouette** [comment]
can you create a new branch with it and send a pull request ?
thanks.

**Comment by dittodhole** [comment]
thought i've already done this ... i've forked your repo, did a commit on my fork, and sent you a pull-request - didn't i?

**Comment by themouette** [comment]
I can see your fork, and I had a quick look to your commits that looks fine, but no pull request in my repo pull request tab.

Just click pull request when browsing your repository in the dedicated branch.

By the way, you've been doing awesome work on the calendar for a long time now, any chance you create pull requests (using different branch is the key) for some of your improvement ?
as long as it is clean and does not break backward compatibility there is no reason it is not merged.

**Comment by dittodhole** [comment]
dah ... forgot the global pushing of the pull-request .. just gathered my commits in a bucket, but didn't commit this ... sry :)

i'll have a look which changes are still needed - some of them are obsolete, as i do some adaptions in the eventHandlers...

**Comment by dittodhole** [comment]
there you go: https://github.com/themouette/jquery-week-calendar/pull/94
